version: '3.8'
services:

  pg:
    # latest or any fresh one, using modern version of postgres method for table's uuid increment
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db_tg_app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
#    networks:
#      - some_network
#    volumes:
#      - pg_data:/var/lib/postgresql/data

#networks:
#  some_network:
#    external: false
#    driver: bridge

#volumes:
#  pg_data: