version: '3.8'
services:

  pg:
    # latest or any fresh one, using modern version of postgres method for table's uuid increment
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db_tg_app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - inner_transfer_calculator_service
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_RUN_PORT:-8000}:8000"
    networks:
      - inner_transfer_calculator_service
    depends_on:
      - pg
    environment:
      - DEBUG=${DEBUG:-False}
      - APP_RUN_HOST=${APP_RUN_HOST:-0.0.0.0}
      - APP_RUN_PORT=${APP_RUN_PORT:-8000}

      - POSTGRES_DB=${POSTGRES_DB:-postgres_db_tg_app}
      - POSTGRES_ECHO=${POSTGRES_ECHO:-False}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE:-10}
      - POSTGRES_MAX_OVERFLOW=${POSTGRES_MAX_OVERFLOW:-20}

      - SQLADMIN_SECRET_KEY=${SQLADMIN_SECRET_KEY:-secret_key_12345}
      - SQLADMIN_USERNAME=${SQLADMIN_USERNAME:-admin}
      - SQLADMIN_PASSWORD=${SQLADMIN_PASSWORD:-password}

      - USD_CURRENCY_CACHE_SEC=${USD_CURRENCY_CACHE_SEC:-1800}
      - OBJECTS_CACHE_SEC=${OBJECTS_CACHE_SEC:-60}
    command: /app/start.sh

networks:
  inner_transfer_calculator_service:
    external: false
    driver: bridge

volumes:
  pg_data: