from datetime import datetime
from .base import BaseResponse
from .provider import ProviderResponse
from .currency import CurrencyResponse


# TODO: Make last_update an autogenerated field with a value of now()


class ExchangeRateResponse(BaseResponse):
    provider: ProviderResponse
    from_currency: CurrencyResponse
    to_currency: CurrencyResponse
    rate: float
    last_updated: datetime
