"""added unique constrains where forgot before

Revision ID: e004e0fbb2d3
Revises: b688654c4f32
Create Date: 2024-08-24 12:33:44.568006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e004e0fbb2d3'
down_revision: Union[str, None] = 'b688654c4f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_countries_name'), 'countries', ['name'])
    op.create_unique_constraint(op.f('uq_documents_name'), 'documents', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_documents_name'), 'documents', type_='unique')
    op.drop_constraint(op.f('uq_countries_name'), 'countries', type_='unique')
    # ### end Alembic commands ###
