"""create country table

Revision ID: 5e5479841ed0
Revises: eeb0b3d2d72b
Create Date: 2024-08-07 17:10:38.106484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5479841ed0'
down_revision: Union[str, None] = 'eeb0b3d2d72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('local_currency_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['local_currency_id'], ['currencies.id'], name=op.f('fk_countries_local_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
