"""create transfer rules table with documents middle relation table

Revision ID: 2c1014ee041e
Revises: 89cf9dcb54d0
Create Date: 2024-08-12 10:41:23.216034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1014ee041e'
down_revision: Union[str, None] = '89cf9dcb54d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_rules',
    sa.Column('send_country_id', sa.UUID(), nullable=False),
    sa.Column('receive_country_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('fee_percentage', sa.Float(), nullable=False),
    sa.Column('min_transfer_amount', sa.Float(), nullable=False),
    sa.Column('max_transfer_amount', sa.Float(), nullable=False),
    sa.Column('transfer_currency_id', sa.UUID(), nullable=False),
    sa.Column('transfer_method', sa.String(), nullable=False),
    sa.Column('min_transfer_time', sa.Interval(), nullable=False),
    sa.Column('max_transfer_time', sa.Interval(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('fee_percentage >= 0 AND fee_percentage < 100', name=op.f('ck_transfer_rules_check_fee_percentage_range')),
    sa.CheckConstraint('min_transfer_amount <= max_transfer_amount', name=op.f('ck_transfer_rules_check_min_max_transfer_amount')),
    sa.ForeignKeyConstraint(['provider_id'], ['transfer_providers.id'], name=op.f('fk_transfer_rules_provider_id_transfer_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receive_country_id'], ['countries.id'], name=op.f('fk_transfer_rules_receive_country_id_countries')),
    sa.ForeignKeyConstraint(['send_country_id'], ['countries.id'], name=op.f('fk_transfer_rules_send_country_id_countries')),
    sa.ForeignKeyConstraint(['transfer_currency_id'], ['currencies.id'], name=op.f('fk_transfer_rules_transfer_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_rules'))
    )
    op.create_index('idx_transfer_rule_currency', 'transfer_rules', ['transfer_currency_id'], unique=False)
    op.create_index('idx_transfer_rule_provider', 'transfer_rules', ['provider_id'], unique=False)
    op.create_index('idx_transfer_rule_receive_country', 'transfer_rules', ['receive_country_id'], unique=False)
    op.create_index('idx_transfer_rule_send_country', 'transfer_rules', ['send_country_id'], unique=False)
    op.create_table('transfer_rule_documents',
    sa.Column('transfer_rule_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_transfer_rule_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['transfer_rule_id'], ['transfer_rules.id'], name=op.f('fk_transfer_rule_documents_transfer_rule_id_transfer_rules')),
    sa.PrimaryKeyConstraint('transfer_rule_id', 'document_id', name='pk_transfer_rule_document')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_rule_documents')
    op.drop_index('idx_transfer_rule_send_country', table_name='transfer_rules')
    op.drop_index('idx_transfer_rule_receive_country', table_name='transfer_rules')
    op.drop_index('idx_transfer_rule_provider', table_name='transfer_rules')
    op.drop_index('idx_transfer_rule_currency', table_name='transfer_rules')
    op.drop_table('transfer_rules')
    # ### end Alembic commands ###
