"""add fixed fee option to rules

Revision ID: e74656268909
Revises: c750c685752c
Create Date: 2024-09-12 18:58:40.445671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e74656268909'
down_revision: Union[str, None] = 'c750c685752c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_rules', sa.Column('fee_fixed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_rules', 'fee_fixed')
    # ### end Alembic commands ###
