"""create countries table

Revision ID: 63d18d2114db
Revises: 40923885371f
Create Date: 2024-08-12 16:42:01.127318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d18d2114db'
down_revision: Union[str, None] = '40923885371f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('local_currency_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['local_currency_id'], ['currencies.id'], name=op.f('fk_countries_local_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('abbreviation', name=op.f('uq_countries_abbreviation'))
    )
    op.create_unique_constraint(op.f('uq_currencies_abbreviation'), 'currencies', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_currencies_abbreviation'), 'currencies', type_='unique')
    op.drop_table('countries')
    # ### end Alembic commands ###
