"""drop unique constrain for rules

Revision ID: 6160ccda58be
Revises: e74656268909
Create Date: 2024-09-13 06:16:07.189389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6160ccda58be'
down_revision: Union[str, None] = 'e74656268909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transfer_rule_unique_combination', 'transfer_rules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transfer_rule_unique_combination', 'transfer_rules', ['send_country_id', 'receive_country_id', 'provider_id', 'transfer_currency_id'])
    # ### end Alembic commands ###
