"""create providers exchange rate table

Revision ID: 40724266b662
Revises: d5fd77b728b6
Create Date: 2024-08-12 16:44:12.330158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40724266b662'
down_revision: Union[str, None] = 'd5fd77b728b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_exchange_rates',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('from_currency_id', sa.UUID(), nullable=False),
    sa.Column('to_currency_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_currency_id'], ['currencies.id'], name=op.f('fk_provider_exchange_rates_from_currency_id_currencies')),
    sa.ForeignKeyConstraint(['provider_id'], ['transfer_providers.id'], name=op.f('fk_provider_exchange_rates_provider_id_transfer_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_currency_id'], ['currencies.id'], name=op.f('fk_provider_exchange_rates_to_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_exchange_rates')),
    sa.UniqueConstraint('provider_id', 'from_currency_id', 'to_currency_id', name='uq_provider_from_to_currency')
    )
    op.create_index('idx_provider_exchange_rate_from_currency', 'provider_exchange_rates', ['from_currency_id'], unique=False)
    op.create_index('idx_provider_exchange_rate_provider', 'provider_exchange_rates', ['provider_id'], unique=False)
    op.create_index('idx_provider_exchange_rate_to_currency', 'provider_exchange_rates', ['to_currency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_exchange_rate_to_currency', table_name='provider_exchange_rates')
    op.drop_index('idx_provider_exchange_rate_provider', table_name='provider_exchange_rates')
    op.drop_index('idx_provider_exchange_rate_from_currency', table_name='provider_exchange_rates')
    op.drop_table('provider_exchange_rates')
    # ### end Alembic commands ###
