"""create transfer providers table

Revision ID: d5fd77b728b6
Revises: 63d18d2114db
Create Date: 2024-08-12 16:43:21.384874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fd77b728b6'
down_revision: Union[str, None] = '63d18d2114db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_transfer_providers_name')),
    sa.UniqueConstraint('url', name=op.f('uq_transfer_providers_url'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_providers')
    # ### end Alembic commands ###
