"""added storage image field to providers table

Revision ID: 02a8540291d0
Revises: f619296e7c4b
Create Date: 2024-08-23 14:43:25.543650

"""
from typing import Sequence, Union

import fastapi_storages
from alembic import op
import sqlalchemy as sa

from core import storage

# revision identifiers, used by Alembic.
revision: str = '02a8540291d0'
down_revision: Union[str, None] = 'f619296e7c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_providers', sa.Column('logo', fastapi_storages.integrations.sqlalchemy.FileType(storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_providers', 'logo')
    # ### end Alembic commands ###
