"""create and populate transfer documents table

Revision ID: 89cf9dcb54d0
Revises: 49e1fcf5d8f0
Create Date: 2024-08-12 10:33:12.345332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89cf9dcb54d0'
down_revision: Union[str, None] = '49e1fcf5d8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )

    # Add predefined documents
    op.execute(
        """
        INSERT INTO documents (name, is_active)
        VALUES 
        ('Passport', True),
        ('International Passport', True),
        ('Driver''s License', True),
        ('ID Card', True)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
