"""create transfer rules table

Revision ID: 182d71148304
Revises: 51fffa618e12
Create Date: 2024-08-06 01:37:57.283765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182d71148304'
down_revision: Union[str, None] = '51fffa618e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_rules',
    sa.Column('send_country_id', sa.UUID(), nullable=False),
    sa.Column('receive_country_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('fee_percentage', sa.Float(), nullable=False),
    sa.Column('min_transfer_amount', sa.Float(), nullable=False),
    sa.Column('max_transfer_amount', sa.Float(), nullable=False),
    sa.Column('transfer_currency_id', sa.UUID(), nullable=True),
    sa.Column('transfer_method', sa.String(), nullable=False),
    sa.Column('estimated_transfer_time', sa.String(), nullable=True),
    sa.Column('required_documents', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['transfer_providers.id'], name=op.f('fk_transfer_rules_provider_id_transfer_providers')),
    sa.ForeignKeyConstraint(['receive_country_id'], ['countries.id'], name=op.f('fk_transfer_rules_receive_country_id_countries')),
    sa.ForeignKeyConstraint(['send_country_id'], ['countries.id'], name=op.f('fk_transfer_rules_send_country_id_countries')),
    sa.ForeignKeyConstraint(['transfer_currency_id'], ['currencies.id'], name=op.f('fk_transfer_rules_transfer_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_rules'))
    )
    op.create_index('idx_transfer_rule_currency', 'transfer_rules', ['transfer_currency_id'], unique=False)
    op.create_index('idx_transfer_rule_provider', 'transfer_rules', ['provider_id'], unique=False)
    op.create_index('idx_transfer_rule_receive_country', 'transfer_rules', ['receive_country_id'], unique=False)
    op.create_index('idx_transfer_rule_send_country', 'transfer_rules', ['send_country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transfer_rule_send_country', table_name='transfer_rules')
    op.drop_index('idx_transfer_rule_receive_country', table_name='transfer_rules')
    op.drop_index('idx_transfer_rule_provider', table_name='transfer_rules')
    op.drop_index('idx_transfer_rule_currency', table_name='transfer_rules')
    op.drop_table('transfer_rules')
    # ### end Alembic commands ###
